# deployment-versions.yaml
# This file controls production deployments and version management
# Only contains the versions to be deployed to production
# Configuration is hardcoded in the Jenkinsfile.deploy for reliability

# ================================================================================
# PRODUCTION VERSIONS
# These are the versions that should be promoted to 'latest' tags
# Only Jenkinsfile.deploy can update 'latest' tags for these versions
# ================================================================================
production:
  app1: "1.3.0"
  app2: "1.3.1"
  # Add more applications as needed:
  # app-name: "X.Y.Z"
